spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console.enabled: true

logging:
  level:
    web: TRACE
