create table test (
    id IDENTITY NOT NULL PRIMARY KEY, -- in case of using JPA annotation @GeneratedValue(strategy = GenerationType.IDENTITY)
                                      -- might be used on the id field of the entity to use autogenerated ids
    text VARCHAR NOT NULL,
    timestamp TIMESTAMP
);
